# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f52952a91daf8d4123c5c8d64f8cee2"
name = "FAQFlow"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"

[app_proxy]
url = "/apps/faqflow"
prefix = "apps"
subpath = "faqflow"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
